# Form implementation generated from reading ui file 'loading_screen.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_loading_screen(object):
    def setupUi(self, loading_screen):
        loading_screen.setObjectName("loading_screen")
        loading_screen.resize(639, 639)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icono.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        loading_screen.setWindowIcon(icon)
        self.progressBar = QtWidgets.QProgressBar(parent=loading_screen)
        self.progressBar.setGeometry(QtCore.QRect(140, 520, 381, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.label = QtWidgets.QLabel(parent=loading_screen)
        self.label.setGeometry(QtCore.QRect(-2, -5, 641, 651))
        self.label.setObjectName("label")
        self.label.raise_()
        self.progressBar.raise_()

        self.retranslateUi(loading_screen)
        QtCore.QMetaObject.connectSlotsByName(loading_screen)

    def retranslateUi(self, loading_screen):
        _translate = QtCore.QCoreApplication.translate
        loading_screen.setWindowTitle(_translate("loading_screen", "CARDIAIGNOSTIC"))
        self.label.setText(_translate("loading_screen", "<html><head/><body><p><img src=\"CardiAIgnostic.jpg\"/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    loading_screen = QtWidgets.QWidget()
    ui = Ui_loading_screen()
    ui.setupUi(loading_screen)
    loading_screen.show()
    sys.exit(app.exec())
