# Form implementation generated from reading ui file 'resultado.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CuadroResultado(object):
    def setupUi(self, CuadroResultado):
        CuadroResultado.setObjectName("CuadroResultado")
        CuadroResultado.resize(400, 136)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icono.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        CuadroResultado.setWindowIcon(icon)
        CuadroResultado.setStyleSheet("background-color: rgb(57, 178, 255);")
        self.widget = QtWidgets.QWidget(parent=CuadroResultado)
        self.widget.setGeometry(QtCore.QRect(10, 10, 381, 80))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.labelResultado = QtWidgets.QLabel(parent=self.widget)
        self.labelResultado.setGeometry(QtCore.QRect(0, 30, 381, 21))
        self.labelResultado.setObjectName("labelResultado")
        self.pushButtonCerrar = QtWidgets.QPushButton(parent=CuadroResultado)
        self.pushButtonCerrar.setGeometry(QtCore.QRect(170, 100, 75, 24))
        self.pushButtonCerrar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButtonCerrar.setObjectName("pushButtonCerrar")

        self.retranslateUi(CuadroResultado)
        QtCore.QMetaObject.connectSlotsByName(CuadroResultado)

        # Conectar el botón "Cerrar" con el método close de la ventana
        self.pushButtonCerrar.clicked.connect(CuadroResultado.close)

    def retranslateUi(self, CuadroResultado):
        _translate = QtCore.QCoreApplication.translate
        CuadroResultado.setWindowTitle(_translate("CuadroResultado", "CARDIAIGNOSTIC"))
        self.labelResultado.setText(_translate("CuadroResultado", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">La persona no presenta una enfermedad cardiaca</span></p></body></html>"))
        self.pushButtonCerrar.setText(_translate("CuadroResultado", "Cerrar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CuadroResultado = QtWidgets.QWidget()
    ui = Ui_CuadroResultado()
    ui.setupUi(CuadroResultado)
    CuadroResultado.show()
    sys.exit(app.exec())
